### ISSUE TITLE
How to set "require password immediately" in .macos?

### ISSUE THREAD

**Issue by kud** [mathiasbynens/dotfiles#822] opened 2018-01-15 13:56 UTC
<img width="555" alt="image" src="https://user-images.githubusercontent.com/655838/34945607-308eb09e-fa04-11e7-8138-f20de04a8bce.png">

**Comment by chdiza** [comment] 2018-01-15 21:50
This is a dupe of #809.  The way to do this pre-High-Sierra no longer works.

**Closed** 2018-01-15 21:57 UTC
