### ISSUE TITLE
Warn about serious possible problems...

### ISSUE THREAD

**Issue by michahell** [mathiasbynens/dotfiles#575] opened 2015-09-15 08:58 UTC
I've forked your dotfiles, removed what I didn't need and added what I already had.
I thought the defaults would be pretty sane, but it appears my macBook now refuses to boot. It might be nice to warn people that there are some serious changes they need to check out first, and not be naive like I was..

Still trying to figure out how to regain access to my system from safe boot :/

**Comment by michahell** [comment] 2015-09-15 09:36
updated issue

**Comment by jgeusebroek** [comment] 2015-09-15 09:38
Why do you think the failure is because of dotfiles, and what does SSD have to do with this?
It's not really clear in your comment.

**Comment by michahell** [comment] 2015-09-15 10:00
well, it's *absolutely* related to dotfiles, as my macbook is practically brand new (3 months old), and i've spent yesterday going through all the dotfiles as I wanted to know what would be configured. 
Yesterday, my macbook booted just fine.
I would't think there would be seriously scary settings aside the startup volume nvram thing, but apparently there are as I'm writing this from a shit citrix workstation while my MacBook is in infinite boot loop, awesome!
I removed the SSD parts just before your reply, I thought there were settings for it but that was unrelated. This is what I did so far:
- Tried safe boot. Won't let me past login, so this is pretty serious somehow.
- reset NVRAM
- reset SMC

**Comment by michahell** [comment] 2015-09-15 10:11
add to the list:
* /sbin/fsck -fy
* mounting '/' volume and trying to:
  * rename .bashrc and .bash_profile to .old and creating new empty ones.

**Comment by michahell** [comment] 2015-09-15 10:19
omg, I give up. This is seriously F-ed up. Will go for a full Yosemite reinstall... I will definitely not recommend anyone to use this dotfiles repo. No idea what caused this, no time to find out. It should never have happened in the first place.

**Comment by michahell** [comment] 2015-09-15 10:30
btw, I'm not the only one who has this issue, #530 is the exact same thing i'm experiencing.
NEW MACBOOK PRO USERS: do NOT just fork this repo and execute bootstrap.sh, wait until this is resolved or resort to other dotfile repo's!

**Comment by guerrero** [comment] 2015-09-15 10:59
Hey @michahell, firstly I ask you to forgive me, I am the comitter of the PR that adds the `defaults` command to enable TRIM support. My apologies for any inconvenience that this change may have caused, I feel really disgusted to know what has happened to you.

I left the TRIM command commented out because: 
- It is unnecesary to use it if you're using a Macbook that comes with an OEM SSD
- It's not supported on OS X versions previous than 10.10.4
- It's not supported by Hard Disk Drives

I thought that people would investigate deeply the pros and possible cons of enable TRIM on a SSD but I was wrong and I apologize for it dude.

Said that, yes, I think that there should be an advice for newcomers explaining that this dotfiles can caouse unexpected behaviours, and I'm going to create a PR to add a warning about this command.

Finally you should know that this dotfiles are specific for Mathias and its Mac. They should work well if you have the same environment and the same configuration so if you change something or use a different environment you should be aware that something can go wrong and act knowing that there may be consequences.

P.S. It would be nice to know your OS X version and SSD brand

**Comment by mathiasbynens** [comment] 2015-09-15 11:00
I’m sorry you’re having this issue. :(

These dotfiles are working for me (and it seems, for others too). I’ve installed them on several Macs and never ran in to the problem you described.

How can you be sure this is related to anything in my dotfiles repo? In one comment you mentioned `bootstrap.sh`, but in another you’re talking about `osx.sh`. Without knowing what/where the cause is, there’s not much I can do. 

I’m closing this issue as there’s nothing actionable in this issue report. Please comment here if you find out anything else.

P.S. Are you by any chance using a non-standard SSD (i.e. not one installed by Apple)?

**Closed** 2015-09-15 11:01 UTC

**Comment by michahell** [comment] 2015-09-15 11:12
Hi guys, sorry for the rants, as usual I tend to get upset very fast when things happen that should not really be allowed to happen :) The way I see dotfiles is that they are mostly (if not all) software configuration settings, not hardware configuration, with the exception of the nvram sound tweak.
So while I did go through all the options (RTFM) I did not encounter anything that I would deem as dangerous stuff..

This is my fork: https://github.com/michahell/dotfiles

Info about my mac:
MacBook Pro (Retina, 15-inch, medio 2015)
15,4"/2,2 Quad-core i7/16 GB/256 GB-Flash

**Comment by guerrero** [comment] 2015-09-15 11:47
No problem @michahell  :), BTW it couldn't be a problem related to TRIM command because you're not using this command in your dotfiles, it doesn't appear even in the master branch of this repo because the original PR is still unmerged :sweat_smile:.

On the other hand, if you're using an OEM SSD it is unwise and unnecessary to use `sudo trimforce enable`. This command disables the check that only allows TRIM to work with Apple-provided OEM flash drives.

**Comment by michahell** [comment] 2015-09-15 11:56
Yes, i've read about that before doing anything with TRIM. Even though it is supposed to be supported from 10.10.4! So this is not the issue. While I was at work I was reading up on FileVault making things worse. Could this be related? Before forking the dotfiles, I had my whole drive FileVault ed?

**Comment by michahell** [comment] 2015-09-15 11:58
Could it be aliases? I mean, is this even safe?
```alias sudo='sudo '```
what about these ```command``` aliases?
```
 Canonical hex dump; some systems have this symlinked
command -v hd > /dev/null || alias hd="hexdump -C"
```
I'm really pissed at myself for not taking this step by step and just rolling with all defaults :/

**Comment by michahell** [comment] 2015-09-15 13:38
Wow. seriously f-ed up! Reinstalled OSX, after reboot, black screen, progress bar, stops at 2/5 and keeps rebooting. What the hell?

**Comment by mathiasbynens** [comment] 2015-09-15 14:35
@michahell Those aliases are definitely safe and unrelated to the problems you’re experiencing.

**Comment by michahell** [comment] 2015-09-15 15:18
@mathiasbynens hmm, ok. I have no idea what files / dotfiles / aliases OSX uses or accesses when booting up, but at least something in these dotfiles caused my system to die in a fire like this. I'll see if I can reproduce this by creating a virtual machine with a fresh Yosemite, cloning my dotfiles and just rebooting. I hope it does, that would at least guarantee my sanity... dang.
